pipeline {
  agent any
  
  stages {
      stage('checkout') {
          steps {
              git 'https://github.com/foconer/spring-jenkins-pipeline.git'
          }
      }
      
      stage('build') {
          steps {
              dir('app-restws') {
                  sh './gradlew clean build'
              } 
          }
      }
  } 
}